### ISSUE TITLE
Switch to async API

### ISSUE THREAD

**Issue by audunhalland** [mikedilger/mime-multipart#12]
This crate is built upon an older, pre-async version of hyper, and as a result the API is also blocking. The hyper ecosystem has moved to async.

I've analyzed a little bit what I think should be done:
* Depend on https://docs.rs/http  instead of hyper
* Depend on https://docs.rs/hyperx for various header parsers
* Change `read_multipart`/`read_multipart_body` to return `futures::stream::Stream` of nodes instead of `Vec`

Will you accept a PR?

**Comment by mikedilger** [comment]
I'm not doing much rust development lately due to a change in employment.

I'm well aware of the move to async throughout the ecosystem.

Yes I would accept a PR.

I think it's also important to continue to support existing pre-async code.  So perhaps an async version should start at 0.20.0 eventually aiming towards 1.0.0, and the pre-async version can continue on the low version numbers if it needs to.  Or something like that (suggestions welcome).

**Comment by audunhalland** [comment]
Thanks for the reply. I looked into this some more, I found that putting work into upgrading this crate would probably be duplicated effort, due to the existence of https://github.com/abonander/multipart and https://github.com/abonander/multipart-async. I was able to use the former crate to get rid of the hyper dependency.

**Comment by mikedilger** [comment]
Glad you've found a path forward.
